/**
 * Conventional Commits, enforced locally by .husky/commit-msg and in CI by the
 * `commits` job in .github/workflows/ci.yml.
 *
 * Worth knowing what this does and does not do here. quadrum's CHANGELOG is
 * generated by **changesets**, from the markdown files in .changeset/ -- not
 * from commit messages. So unlike a release-please repo, a `feat:` prefix does
 * not create a changelog entry or bump a version. What it buys is a readable,
 * greppable history and one convention across repos; the changelog is the
 * changeset's job, and CI checks for that separately.
 */
export default {
	extends: ["@commitlint/config-conventional"],
	rules: {
		// The types config-conventional allows, minus `improvement` and plus the
		// ones this repo actually uses. Listing them explicitly means a typo like
		// `chores:` fails instead of quietly becoming a new category.
		"type-enum": [
			2,
			"always",
			[
				"feat", // a user-facing capability
				"fix", // a defect repaired
				"perf", // faster or lighter, same behaviour
				"refactor", // behaviour-preserving restructure
				"docs", // README, architecture.md, comments
				"test", // specs only, no shipped code
				"build", // tsup, tsconfig, packaging, dependencies
				"ci", // workflows and release automation
				"chore", // housekeeping that fits nothing above
				"revert",
			],
		],

		// Subjects stay lower-case after the colon, matching the rest of the
		// history. config-conventional bans sentence/start/pascal/upper case;
		// this is that rule stated outright so the intent is obvious.
		"subject-case": [2, "never", ["sentence-case", "start-case", "pascal-case", "upper-case"]],

		// 72 leaves room for git log's 4-space indent inside an 80-column terminal.
		"header-max-length": [2, "always", 72],

		// Bodies wrap; a wall of text in one line is unreadable in `git log`.
		// Warning rather than error -- a pasted stack trace is a fair exception.
		"body-max-line-length": [1, "always", 100],
	},
	ignores: [
		// Merge commits and changesets' own release commits are machine-written
		// and do not follow the convention.
		(message) => message.startsWith("Merge "),
		(message) => message.startsWith("Version Packages"),

		// Dependabot's messages, which .github/dependabot.yml already shapes into
		// `chore(deps): ...` / `ci(deps): ...`. They are exempt from the rest --
		// specifically header-max-length, since "bump @commitlint/config-conventional
		// from 21.2.0 to 21.2.1" blows past 72 with a name that long and the bot
		// cannot be told to shorten it. The prefix is checked here rather than the
		// author, because the `commits` job also lints the PR *title*, where no
		// author is available.
		(message) => /^(chore|ci)\(deps(-dev)?\)(!)?: /.test(message),
	],
};
